// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFBEcslhnSq8SfEUo6Ld-iJmORU2tho3Y',
    appId: '1:229968319813:web:272df55c829b17652b9a2c',
    messagingSenderId: '229968319813',
    projectId: 'fitfocus-334b7',
    authDomain: 'fitfocus-334b7.firebaseapp.com',
    storageBucket: 'fitfocus-334b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdJQOhePy7YEPX99mqVnbVAdGwaEsLQ10',
    appId: '1:229968319813:android:60207476a1edf8422b9a2c',
    messagingSenderId: '229968319813',
    projectId: 'fitfocus-334b7',
    storageBucket: 'fitfocus-334b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLnlVjcW6Pu2we24kyOFC7wb4fvg4psw',
    appId: '1:229968319813:ios:fe51cbf94a01716a2b9a2c',
    messagingSenderId: '229968319813',
    projectId: 'fitfocus-334b7',
    storageBucket: 'fitfocus-334b7.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsLnlVjcW6Pu2we24kyOFC7wb4fvg4psw',
    appId: '1:229968319813:ios:fe51cbf94a01716a2b9a2c',
    messagingSenderId: '229968319813',
    projectId: 'fitfocus-334b7',
    storageBucket: 'fitfocus-334b7.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFBEcslhnSq8SfEUo6Ld-iJmORU2tho3Y',
    appId: '1:229968319813:web:50f7c25b5765977a2b9a2c',
    messagingSenderId: '229968319813',
    projectId: 'fitfocus-334b7',
    authDomain: 'fitfocus-334b7.firebaseapp.com',
    storageBucket: 'fitfocus-334b7.firebasestorage.app',
  );
}
